# Generated by Django 5.2.6 on 2025-09-09 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
